/* Server version: WI-V6.3.1.26351 Firebird 2.5 
   SQLDialect: 3. ODS: 11.1. Forced writes: On. Sweep inteval: 20000.
   Page size: 8192. Cache pages: 2048 (16384 Kb). Read-only: False. */
SET SQL DIALECT 3;

CONNECT 'D:\NAO ABRA\NAO\Projetos\Projeto Monitor Dimas\Base PDV\PDV\PDV.FDB' USER 'SYSDBA' PASSWORD 'masterkey';

SET AUTODDL ON;

ALTER TABLE ITENSCLASSIFICACOESFISCAIS ADD CSOSN DOMINTEIRO NOT NULL;

ALTER TABLE VENDAS ADD STATUSNF VARCHAR(10);

ALTER TABLE VENDAS ADD CHAVE VARCHAR(250);

ALTER TABLE VENDAS ADD CAMINHOXML VARCHAR(2500);

